[book]
title = "The cutler Cookbook"
author = "HitBlast"
description = "Documentation for cutler - a fast, declarative settings manager for the Mac"
language = "en"
src = "src"

[output.html]
default-theme = "mdbook-brew"
preferred-dark-theme = "mdbook-brew"
additional-css = ["./theme/mdbook-brew.css"]

[output.html.search]
limit-results = 15
